= Containerized Release Scripting

Welcome to a containerized release process for mod_cluster container integration modules (or any `maven-release-plugin` released project from GitHub really).

Easy, reproducible, secure.

== Building Release Container Image

In case you need to rebuild the container release image, build and deploy as follows.
Using `podman` and `quay.io` run:

[source,shell]
----
podman build --no-cache -t mod_cluster/mod_cluster-java-release:main .
echo "unqualified-search-registries = [\"quay.io\"]" >> ~/.config/containers/registries.conf
podman login
podman push modcluster-java-release:main quay.io/mod_cluster/mod_cluster-java-release
----

== Steps

. Prepare https://github.com/modcluster/mod_cluster branch for release.
. Tag the release using `maven-release-plugin`.

[source,shell]
----
mvn release:prepare -DautoVersionSubmodules=true
----

. Inspect, verify the tag and push it upstream (since 1.4 release plugin is configured to do this automatically,
  thus make sure to verify branch before preparing the release):

[source,shell]
----
git push upstream
git push upstream 2.1.0.Final
----

. Perform a release using the container image changing the parameters as necessary:

[source,shell]
----
export JBOSS_USERNAME=username
export JBOSS_PASSWORD=password
podman run -e TAG=1.4.0.Final -e JAVA_VERSION=11 -e JBOSS_USERNAME -e JBOSS_PASSWORD mod_cluster/mod_cluster-java-release:main
----

. Check, close and promote the staging repository: https://repository.jboss.org/nexus/index.html#stagingRepositories

. Release version in Jira: https://issues.redhat.com/plugins/servlet/project-config/MODCLUSTER/administer-versions

== Testing

To test or release custom branches from custom GitHub repositories,
you can set up the release step with `GITHUB_ORGANIZATION` and `GITHUB_REPOSITORY`:

[source,shell]
----
podman run -e TAG=MODCLUSTER-686 -e GITHUB_ORGANIZATION=rhusar -e GITHUB_REPOSITORY=mod_cluster -e JBOSS_USERNAME -e JBOSS_PASSWORD modcluster/mod_cluster-java-release:main
----

Enjoy. ― Rado
